### PR TITLE
Bump CPG to `1.3.49`

### PR DESCRIPTION
**Pull request by ursachec**

### CODE REVIEW

**Review by fabsx00 — APPROVED** [review]

**Comment by ursachec** [comment]
Build is failing because SonaType has not published 1.3.49 yet. All seems good on our side, not sure what's taking so long

**Comment by fabsx00** [comment]
Build now seems to be failing at the new `joern-scan` integration test.

**Comment by fabsx00** [comment]
Btw, I haven't placed the default query-db version in a separate file yet, so, to update to v0.0.50, you need to edit `JoernScan.scala`.

**Comment by fabsx00** [comment]
Try upgrading to 0.0.50 first, I can imagine that resolves it.

**Comment by ursachec** [comment]
hmm, not sure what part's causing the problem...guess the error handling needs some work.
and 1.3.49 still not public on sonatype

**Comment by fabsx00** [comment]
```
 ./joern-scan --dump
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaVanillaMethodMirror0.jinvokeraw(JavaMirrors.scala:419)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaMethodMirror.jinvoke(JavaMirrors.scala:395)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaVanillaMethodMirror.apply(JavaMirrors.scala:411)
	at io.shiftleft.console.QueryDatabase.$anonfun$queriesInBundle$1(QueryDatabase.scala:67)
	at scala.collection.immutable.List.map(List.scala:246)
	at io.shiftleft.console.QueryDatabase.queriesInBundle(QueryDatabase.scala:65)
	at io.shiftleft.console.QueryDatabase.$anonfun$allQueries$1(QueryDatabase.scala:57)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at io.shiftleft.console.QueryDatabase.allQueries(QueryDatabase.scala:56)
	at io.shiftleft.joern.JoernScan$.dumpQueries(JoernScan.scala:97)
	at io.shiftleft.joern.JoernScan$.runScanner(JoernScan.scala:72)
	at io.shiftleft.joern.JoernScan$.$anonfun$new$8(JoernScan.scala:67)
	at io.shiftleft.joern.JoernScan$.$anonfun$new$8$adapted(JoernScan.scala:66)
	at scala.Option.foreach(Option.scala:437)
	at io.shiftleft.joern.JoernScan$.delayedEndpoint$io$shiftleft$joern$JoernScan$1(JoernScan.scala:66)
	at io.shiftleft.joern.JoernScan$delayedInit$body.apply(JoernScan.scala:27)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at io.shiftleft.joern.JoernScan$.main(JoernScan.scala:27)
	at io.shiftleft.joern.JoernScan.main(JoernScan.scala)
Caused by: java.lang.NoSuchMethodError: io.shiftleft.console.Query$.apply$default$10()Lscala/collection/immutable/List;
	at io.joern.scanners.c.IntegerTruncations$.strlenAssignmentTruncations(IntegerTruncations.scala:17)
	... 32 more
```

**Review by davyhua — APPROVED** [review]

**Pull request merged**
